microsoft/graphitation

change/@graphitation-apollo-mock-client-7626950b-0b66-45c1-b957-91f5fb0c2448.json
change/@graphitation-apollo-react-relay-duct-tape-08870c4f-edac-4ead-bbe7-c4a553625f05.json
change/@graphitation-graphql-js-operation-payload-generator-4360a8ae-9b78-4721-998b-94c02c9bd0ce.json
change/@graphitation-graphql-js-tag-9a143d19-e885-4e38-8d21-3f37fa76abef.json
change/relay-compiler-language-graphitation-22a3d55f-76f5-48f3-8031-7c45e100a130.json
packages/apollo-mock-client/package.json
packages/apollo-react-relay-duct-tape/package.json
packages/graphql-js-operation-payload-generator/package.json
packages/graphql-js-tag/package.json
packages/relay-compiler-language-graphitation/package.json

syncs the version in the npmjs.org registry with what is checked into the package.json

fixes publishing

---

package.json
yarn.lock

I have identified some source of slowness in the tools. This bumps those deps to make the dev experience way better :)

bumps tools so they boot up faster

---

change/@graphitation-apollo-react-relay-duct-tape-0021a36f-d27a-4635-80b4-f2f6d433a585.json
packages/apollo-react-relay-duct-tape/src/__tests__/__generated__/hooksTestMutation.graphql.ts
packages/apollo-react-relay-duct-tape/src/__tests__/hooks.test.tsx
packages/apollo-react-relay-duct-tape/src/__tests__/schema.graphql
packages/apollo-react-relay-duct-tape/src/hooks.ts

```ts
const mutation = graphql`
mutation SomeReactComponentMutation($newName: String!) {
someMutation(newName: $newName) {
__typeName
id
newName
}
}
`
export const SomeReactComponent: React.FunctionComponent<SomeReactComponentProps> = props => {
const [commitMutation, isInFlight] = useMutation(mutation);
return (
<div>
<button onClick={() => commitMutation({
variables: {
newName: "foo"
},
optimisticResponse: {
someMutation: {
__typename: "SomeMutationPayload",
id: "1",
newName: "foo",
}
}
})} disabled={isInFlight}/>
</div>
);
}```

Add "useMutation" hook

---

change/@graphitation-graphql-js-operation-payload-generator-83d5a4b6-7665-4c7b-8066-f95011486de8.json
packages/graphql-js-operation-payload-generator/package.json
packages/graphql-js-operation-payload-generator/src/__tests__/RelayMockPayloadGenerator.test.ts
packages/graphql-js-operation-payload-generator/src/__tests__/__snapshots__/RelayMockPayloadGenerator.test.ts.snap
packages/graphql-js-operation-payload-generator/src/index.ts

Deeply merge fragment data

---

change/@graphitation-ts-transform-graphql-js-tag-96a81779-fc50-4cfc-b711-85f175ee23e4.json
packages/ts-transform-graphql-js-tag/.eslintrc.json
packages/ts-transform-graphql-js-tag/.npmignore
packages/ts-transform-graphql-js-tag/README.md
packages/ts-transform-graphql-js-tag/package.json
packages/ts-transform-graphql-js-tag/src/index.test.ts
packages/ts-transform-graphql-js-tag/src/index.ts
packages/ts-transform-graphql-js-tag/src/transformerTestUtils.ts
packages/ts-transform-graphql-js-tag/tsconfig.json
yarn.lock

Add a ts-transform-graphql-js-tag - a library to transform gql strings into document definitions.

ts transform graphql js tag

---

change/@graphitation-supermassive-15a9495e-d7e6-4906-9d3c-81a9e51459db.json
packages/supermassive/README.md

Rendered version: https://github.com/microsoft/graphitation/blob/alloy/supermassive-readme/packages/supermassive/README.md

[supermassive/doc] Expand on what/why/how

---

examples/apollo-watch-fragments/src/App.tsx
examples/apollo-watch-fragments/src/TodoList.tsx
examples/apollo-watch-fragments/src/__generated__/AppQuery.graphql.ts
examples/apollo-watch-fragments/src/__generated__/TodoListPaginationQuery.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/__generated__/compiledHooks_ForwardPaginationFragment_PaginationQuery.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/__generated__/compiledHooks_Root_executionQuery.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/compiledHooks.test.tsx

Closes #84
Closes #83
The assumption was that we needed to extract default values and persist those in our ‘context’, but that actually didn’t turn out to be true. As long as we don't override a variable in a refetch, the default value will be used as defined in the operation variables definitions. Thus, this PR only demonstrates it working, no implementation changes were made.

[ARRDT] Verify that variables with default values and @argumentDefinitions work

---

change/@graphitation-apollo-mock-client-8149ea35-d1c2-4ea8-910e-df21d4dd1b46.json
change/@graphitation-apollo-react-relay-duct-tape-bfbe57fb-25e8-46a6-b2f2-c93f40c0209a.json
change/@graphitation-graphql-eslint-rules-9db10fe6-c90f-4ae3-b164-549f2bdb79c8.json
change/@graphitation-graphql-js-operation-payload-generator-f8fc88d4-df01-45f4-b2f8-e2c97d974c18.json
change/@graphitation-supermassive-35d47faf-b2b2-433d-8aa9-41b17812c31d.json
change/@graphitation-ts-transform-graphql-js-tag-9effb686-ae27-44d3-a45f-4f809180f442.json
change/relay-compiler-language-graphitation-458163b7-4aae-49bf-91eb-e79b35d02d9b.json
package-template/package.json
packages/apollo-mock-client/package.json
packages/apollo-mock-client/src/__tests__/RelayMockEnvironmentWithComponents.test.tsx
packages/apollo-react-relay-duct-tape/package.json
packages/apollo-react-relay-duct-tape/src/__tests__/hooks.test.tsx
packages/graphql-eslint-rules/package.json
packages/graphql-js-operation-payload-generator/package.json
packages/relay-compiler-language-graphitation/package.json
packages/supermassive/package.json
packages/supermassive/src/executeWithSchema.ts
packages/supermassive/src/subscribeWithSchema.ts
packages/ts-transform-graphql-js-tag/package.json

Change main format to support webpack 4.
Make default imports for third-party CommonJS dependencies or remove them

Fix Webpack 4 compat

---

packages/apollo-react-relay-duct-tape/src/storeObservation/nodeFromCacheFieldPolicy.ts

Related to #113 
Follow-up work defined in https://github.com/microsoft/graphitation/issues/126

[ARRDT] Use Apollo cache redirect instead of reading from cache ourselves

---

examples/apollo-watch-fragments/package.json
examples/apollo-watch-fragments/src/__generated__/TodoListFooter_todosFragment.graphql.ts
examples/apollo-watch-fragments/src/__generated__/TodoListPaginationQuery.graphql.ts
examples/apollo-watch-fragments/src/__generated__/TodoList_queryFragment.graphql.ts
examples/apollo-watch-fragments/src/__generated__/TodoRefetchQuery.graphql.ts
examples/apollo-watch-fragments/src/__generated__/Todo_todoFragment.graphql.ts
examples/apollo-watch-fragments/src/graphql.ts
examples/supermassive-todomvc/package.json
package.json
packages/apollo-react-relay-duct-tape/package.json
packages/apollo-react-relay-duct-tape/src/__tests__/__generated__/hooksTestFragment.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/__generated__/compiledHooks_BackwardPaginationFragment.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/__generated__/compiledHooks_ChildFragment.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/__generated__/compiledHooks_ForwardPaginationFragment.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/__generated__/compiledHooks_QueryTypeFragment.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/__generated__/compiledHooks_RefetchableFragment.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/__generated__/compiledHooks_Root_executionQuery.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/compiledHooks.test.tsx
packages/apollo-react-relay-duct-tape/src/storeObservation/createImportDocumentsTransform.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/nodeFromCacheFieldPolicy.test.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/nodeFromCacheFieldPolicy.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/typePolicies.ts
website/package.json
yarn.lock

Includes the change from #134, which should be merged first.

[ARRDT] Bump typescript

---

.azure-devops/graphitation-release.yml
change/@graphitation-graphql-eslint-rules-824a89b0-36f6-408e-91c8-0d166936cd81.json
packages/graphql-eslint-rules/package.json

This time, I'm following what FluentUI does: by changing the git origin URL to include the user name & password.

fix release try #2

---

.azure-devops/graphitation-release.yml

Cargo-culting from the FluentUI repo: https://github.com/microsoft/fluentui/blob/855ec38026ff54ddf929a9e540abbf58d5b6ba78/azure-pipelines.release.yml

[ci] Add tasks to generate sbom

---

.azure-devops/steps/pierce-ado-npm-mirror-cache.yml
change/@graphitation-graphql-eslint-rules-248db7c6-abe8-415f-aca5-20bf37a6801d.json
packages/graphql-eslint-rules/README.md

This is just a dummy publish to exercise the newly minted publish scripts steps (SBOM)

Chore: try dummy publish

---

change/@graphitation-graphql-codegen-supermassive-schema-extraction-plugin-e21e5453-b076-40b9-a49b-ec7227c9833c.json
change/@graphitation-graphql-js-operation-payload-generator-5bb40f14-cc38-4e1a-ae69-e8a5e7702794.json
packages/graphql-codegen-supermassive-schema-extraction-plugin/package.json
packages/graphql-js-operation-payload-generator/package.json

Fixes missing dependencies in schema plugin & payload generator packages

Fix missing dependencies in schema plugin & payload generator

---

change/@graphitation-apollo-react-relay-duct-tape-compiler-d9316c01-333c-456e-9919-08464bbb0bec.json
change/@graphitation-apollo-react-relay-duct-tape-e8e17c9f-f652-44c1-ac7d-2d3542fb1d51.json
change/@graphitation-embedded-document-artefact-loader-8520a1ce-d4e9-461d-a2b4-bc7443419dae.json
examples/apollo-watch-fragments/package.json
examples/apollo-watch-fragments/src/Todo.tsx
examples/apollo-watch-fragments/src/TodoList.tsx
examples/apollo-watch-fragments/src/TodoListFooter.tsx
examples/apollo-watch-fragments/src/__generated__/AppQuery.graphql.ts
examples/apollo-watch-fragments/src/__generated__/TodoListFooter_todosWatchNodeQuery.graphql.ts
examples/apollo-watch-fragments/src/__generated__/TodoListPaginationQuery.graphql.ts
examples/apollo-watch-fragments/src/__generated__/TodoRefetchQuery.graphql.ts
examples/apollo-watch-fragments/src/__generated__/useAddTodoMutation.graphql.ts
examples/apollo-watch-fragments/src/__generated__/useChangeTodoStatusMutation.graphql.ts
examples/apollo-watch-fragments/src/useAddTodoMutation.ts
examples/apollo-watch-fragments/webpack.config.ts
packages/apollo-react-relay-duct-tape-compiler/src/formatModule.ts
packages/apollo-react-relay-duct-tape/src/hooks.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/shallowCompareFragmentReferences.ts
packages/embedded-document-artefact-loader/package.json
packages/embedded-document-artefact-loader/src/__tests__/__snapshots__/webpack.test.ts.snap
packages/embedded-document-artefact-loader/src/__tests__/webpack.test.ts
packages/embedded-document-artefact-loader/src/source-map-utils.ts
packages/embedded-document-artefact-loader/src/transform.ts

Bring everything together for duct tape

---

.azure-devops/steps/compliance-steps.yml

There's a need to release this software with a new ADO org. This is a PR that changes all that is needed to migrate it.

migration of the pipeline

---

change/@graphitation-supermassive-b5897e0b-f3e9-405d-a2b5-6f06e27aa086.json
packages/supermassive/src/executeWithoutSchema.ts

`isTotalExecutionResult` seems to have the wrong type assertion. Probably a copy paste error from `isIncrementalExecutionResult` above?

Fix type assertion for isTotalExecutionResult

---

change/@graphitation-apollo-react-relay-duct-tape-b2698eab-872c-4068-b6f9-58eb6613bbf9.json
packages/apollo-react-relay-duct-tape/src/storeObservation/__tests__/__snapshots__/compiledHooks.test.tsx.snap
packages/apollo-react-relay-duct-tape/src/storeObservation/__tests__/compiledHooks.test.tsx
packages/apollo-react-relay-duct-tape/src/storeObservation/compiledHooks/useCompiledLazyLoadQuery.ts

Using custom fetchPolicy while executing queries.

Using custom fetch-policy while lazyloading queries.

---

examples/apollo-watch-fragments/data/schema.graphql
examples/apollo-watch-fragments/src/TodoList.tsx
examples/apollo-watch-fragments/src/__generated__/AppQuery.graphql.ts
examples/apollo-watch-fragments/src/__generated__/TodoListPaginationQuery.graphql.ts
examples/apollo-watch-fragments/src/graphql.ts
examples/apollo-watch-fragments/src/graphql/resolver-typings.ts

This PR reproes #401 in apollo-watch-fragments example

Repro of #401

---

change/@graphitation-graphql-codegen-supermassive-typed-document-node-plugin-dc271054-e502-4763-824e-fe540b92c6cf.json
packages/graphql-codegen-supermassive-typed-document-node-plugin/src/visitor.ts

Allow generating plain graphql-js AST.

[@graphitation/graphql-codegen-supermassive-typed-document-node-plugin] add none option to typed document node

---

change/@graphitation-graphql-eslint-rules-90b8d5e7-8a07-481d-a015-bdacbff24eaa.json
packages/graphql-eslint-rules/src/__tests__/__snapshots__/ban-directives.test.ts.snap
packages/graphql-eslint-rules/src/__tests__/ban-directives.test.ts
packages/graphql-eslint-rules/src/ban-directives.ts
packages/graphql-eslint-rules/src/fragment-naming-conventions.ts
packages/graphql-eslint-rules/src/index.ts
packages/graphql-eslint-rules/src/missing-apollo-key-fields.ts
packages/graphql-eslint-rules/src/operation-naming-conventions.ts
patches/@graphql-eslint+eslint-plugin+3.7.0.patch

Adds ban directives rule to the package. 
(also fixes typing issue in graphql-eslint plugin)

Add ban-directives rule

---

.azure-devops/graphitation-release.yml

Update agent pools in graphitation-release.yml

---

change/@graphitation-ts-transform-graphql-js-tag-fe655d64-6956-403e-96f6-5d2b1b7fa689.json
packages/ts-transform-graphql-js-tag/package.json
packages/ts-transform-graphql-js-tag/src/index.ts
packages/ts-transform-graphql-js-tag/src/transformerTestUtils.ts
yarn.lock

Update ts-morph/bootstrap and ts api calls to be compatible with TypeScript 5.5.

Update ts-transform to be compat with ts 5.5

---

.config/1espt/PipelineAutobaseliningConfig.yml

…a124-7146354d472f/_build?definitionId=8 by using baselines generated in https://dev.azure.com/DomoreexpGithub/48875bf1-082b-425a-a124-7146354d472f/_build/results?buildId=1282

feat(pipeline): 1espt config

---

.vscode/settings.json
change/@graphitation-apollo-react-relay-duct-tape-compiler-9f7504fc-1bd1-4c80-a144-347fe5f2e8b6.json
packages/apollo-react-relay-duct-tape-compiler/src/typescriptTransforms/TypeScriptGenerator.ts
packages/apollo-react-relay-duct-tape-compiler/src/typescriptTransforms/__tests__/TypeScriptGenerator.test.ts
packages/apollo-react-relay-duct-tape-compiler/src/typescriptTransforms/__tests__/__snapshots__/TypeScriptGenerator.test.ts.snap
packages/apollo-react-relay-duct-tape-compiler/src/typescriptTransforms/__tests__/fixtures/type-generator/query-with-mering-scalars.error.graphql
packages/apollo-react-relay-duct-tape-compiler/src/typescriptTransforms/__tests__/fixtures/type-generator/query-with-mering-scalars.graphql
patches/relay-compiler+12.0.0.patch

When we have union, one field is array of some type and the same field in different type is array of scalar we are throwing an error.

Compiler: merging scalar and object error

---

.azure-devops/graphitation-release.yml
.azure-devops/steps/pierce-ado-npm-mirror-cache.yml

tested by: https://github.com/microsoft/graphitation/pull/514
```bash
fatal: ambiguous argument 'HEAD~1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

fix(pipeline): mirroring of packages

---

change/@graphitation-ts-codegen-33ca5c68-b3af-4f48-b375-ba4ba0114d51.json
packages/ts-codegen/src/__tests__/context.test.ts
packages/ts-codegen/src/__tests__/index.test.ts
packages/ts-codegen/src/context/__tests__/import.test.ts
packages/ts-codegen/src/context/import.ts
packages/ts-codegen/src/context/index.ts

feat(ts-codegen): translate @import into namespace imports

---

examples/supermassive-todomvc/CHANGELOG.json
examples/supermassive-todomvc/CHANGELOG.md
examples/supermassive-todomvc/package.json
website/package.json
website/yarn.lock

mermaid 10.0.3 fix the security issue, this PR bumping the version to the safe one. https://github.com/cure53/DOMPurify/security/advisories/GHSA-mmhx-hmjr-r674

feat(website): bump docusaurus

---

change/@graphitation-apollo-forest-run-3128091f-1aab-4385-a1bb-e535389e19d8.json
packages/apollo-forest-run/src/cache/descriptor.ts
packages/apollo-forest-run/src/cache/keys.ts
packages/apollo-forest-run/src/cache/store.ts
packages/apollo-forest-run/src/cache/types.ts
packages/apollo-forest-run/src/cache/write.ts
packages/apollo-forest-run/src/descriptor/__tests__/operation.test.ts
packages/apollo-forest-run/src/descriptor/operation.ts
packages/apollo-forest-run/src/descriptor/types.ts
packages/apollo-forest-run/src/jsutils/normalize.ts

perf(apollo-forest-run): store operations by key constructed from variables
