microsoft/graphitation

.github/workflows/release.yml

This will enable the release to occur every time the main is merged. The release job will only actually release things when change files are detected. Otherwise, it will simply run a build & test on the main branch at that time.

auto release on merge of main

---

change/@graphitation-apollo-react-relay-duct-tape-6a977859-79fe-4c56-8e66-511a32d9687b.json
change/monorepo-scripts-3900d756-3cc8-46d3-b3c3-6e716a345f9f.json
change/relay-compiler-language-graphitation-cd82f35a-cd95-416e-bf96-70c5a3b1cf62.json
packages/apollo-react-relay-duct-tape/README.md
packages/apollo-react-relay-duct-tape/package.json
packages/apollo-react-relay-duct-tape/src/__tests__/__generated__/hooksTestFragment.graphql.ts
packages/apollo-react-relay-duct-tape/src/__tests__/__generated__/hooksTestQuery.graphql.ts
packages/apollo-react-relay-duct-tape/src/__tests__/__generated__/hooksTestSubscription.graphql.ts
packages/apollo-react-relay-duct-tape/src/__tests__/hooks.test.tsx
packages/relay-compiler-language-graphitation/README.md
packages/relay-compiler-language-graphitation/package.json
packages/relay-compiler-language-graphitation/src/findGraphQLTags.ts
packages/relay-compiler-language-graphitation/src/formatModule.ts
packages/relay-compiler-language-graphitation/src/index.ts
packages/relay-compiler-language-graphitation/src/rewriteGraphitationDirectives.ts
packages/relay-compiler-language-graphitation/src/typeGenerator.ts
packages/relay-compiler-language-graphitation/tsconfig.json
scripts/just.config.ts
yarn.lock

A relay-compiler plugin that wraps [the TypeScript plugin](https://github.com/relay-tools/relay-compiler-language-typescript) and augments it slightly for our needs:
- Currently only emit typings, no relay-runtime metadata
- Allow interpolation of GraphQL fragment documents
- Rewrite `@graphitation_test_operation` to relay-compiler's `@raw_response_type` -- _this will likely be removed short-term_
- Rewrite `relay-runtime` import in generated artefacts to `@graphitation/apollo-react-relay-duct-tape`
- Strip `__isFoo` fields from raw response typings, which is something that relay-runtime needs

Add graphitation specific wrapper around relay-compiler typescript plugin

---

change/@graphitation-graphql-js-operation-payload-generator-39874ff5-a602-4cdc-8aa3-307ef52c0045.json
packages/graphql-js-operation-payload-generator/src/__tests__/RelayMockPayloadGenerator.test.ts
packages/graphql-js-operation-payload-generator/src/__tests__/__snapshots__/RelayMockPayloadGenerator.test.ts.snap
packages/graphql-js-operation-payload-generator/src/index.ts
packages/graphql-js-operation-payload-generator/src/vendor/RelayMockPayloadGenerator.ts

In case of an abstract type the user can specify a mock that returns a specific typename, in which case the appropriate fragment spread should be selected.

Support explicit concrete type selection

---

change/@graphitation-graphql-js-operation-payload-generator-593b7df5-c7f3-468b-829e-bb9d4b183be2.json
packages/graphql-js-operation-payload-generator/src/__tests__/RelayMockPayloadGenerator.test.ts
packages/graphql-js-operation-payload-generator/src/__tests__/__snapshots__/RelayMockPayloadGenerator.test.ts.snap
packages/graphql-js-operation-payload-generator/src/index.ts

The existing test case didn’t cover what we actually do in TMP.

Support explicit concrete type selection across mutliple fragment spreads

---

yarn.lock

Bump path-parse from 1.0.6 to 1.0.7 in /examples/apollo-watch-fragments

---

examples/apollo-watch-fragments/src/__generated__/AppQuery.graphql.ts
examples/apollo-watch-fragments/src/__generated__/TodoListFooter_todosWatchNodeQuery.graphql.ts
examples/apollo-watch-fragments/src/__generated__/TodoListPaginationQuery.graphql.ts
examples/apollo-watch-fragments/src/__generated__/TodoRefetchQuery.graphql.ts
examples/apollo-watch-fragments/src/__generated__/useAddTodoMutation.graphql.ts
examples/apollo-watch-fragments/src/__generated__/useChangeTodoStatusMutation.graphql.ts
packages/relay-compiler-language-graphitation/package.json
packages/relay-compiler-language-graphitation/src/formatModule.ts
yarn.lock

Support [@graphql-tools/optimize](https://github.com/ardatan/graphql-tools/tree/master/packages/optimize) for smaller AST size. By default optimizers will: remove descriptions, remove empty optional properties (like `arguments: []` or `directives: []`) and remove locations if they exist.
One minor issue with this package is that each optimizer does a separate `visit` pass over a document, so it will perform 3 additional passes. I think it's OK-ish for build-time tools though.

[relay-compiler-language-graphitation] optimize AST size

---

examples/apollo-watch-fragments/public/index.html
examples/apollo-watch-fragments/webpack.config.ts

This sets up React Render Tracker in the example to work for anyone.
@lahmatiy Do you think this is an acceptable generic solution that we can add to your README?

[example] Configure source-maps for React Render Tracker to open editor

---

change/relay-compiler-language-graphitation-76b539a4-8840-4406-adb6-0a246d482c46.json
packages/relay-compiler-language-graphitation/package.json
yarn.lock

We were facing an error in `relay-compiler-language-typescript: 14.0.0.` issue described [here](https://github.com/relay-tools/relay-compiler-language-typescript/issues/513), which caused a syntax error in generated files.
With `>=14.0.0` in this update we wanted to not force apps which use the graphitation plugin to have TS version 4.5 or greater.

Relay compiler language graphitation/dependency update

---

change/relay-compiler-language-graphitation-6550d47d-e88f-494e-ac11-b1f462a9b7d1.json
packages/relay-compiler-language-graphitation/package.json
yarn.lock

typecript version changed from ^4.2.3 to >=4.2.3 based on [PR #78 ](https://github.com/microsoft/graphitation/pull/78)

Relay compiler language graphitation/typescript update

---

change/@graphitation-supermassive-23b2314a-ae06-4bc4-8602-23a1db17c751.json
packages/supermassive/package.json
packages/supermassive/tsconfig.json
yarn.lock

This PR does two things for the `supermassive` package: 
1. "Unpins" `typescript` dependency from a fixed version. Now it is the same as in: 
https://github.com/microsoft/graphitation/blob/62cc911d8b0a6bea8cab19ad35f2b672a14a7a4d/packages/ts-transform-graphql-js-tag/package.json#L39
2. Allows running `benchmark` command on Windows (it currently fails)

chore: package.json fixes for supermassive

---

packages/apollo-react-relay-duct-tape/src/storeObservation/compiledHooks.test.tsx
packages/apollo-react-relay-duct-tape/src/storeObservation/compiledHooks/useCompiledPaginationFragment.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/compiledHooks/useCompiledRefetchableFragment.ts
website/docs/apollo-react-relay-duct-tape/use-pagination-fragment.md
website/docs/apollo-react-relay-duct-tape/use-refetchable-fragment.md

Fixes #105 
I had missed in Relay's source that this is done for any refetch query. Also adding it to the [upstream] docs.

[ARRDT] Dispose any refetch query on unmount

---

change/@graphitation-supermassive-55603d20-15bc-448f-bb08-929dfa343306.json
packages/supermassive/src/__tests__/subscribe.test.ts
packages/supermassive/src/values.ts

When the `variableValues` doesn't contain variableName, which is specified in function arguments AND it isn't `isNonNullType` (it's not required) we just want to skip it

Supermassive get argument values fix

---

packages/apollo-react-relay-duct-tape/src/storeObservation/nodeFromCacheFieldPolicy.ts

This will help us re-use the same optimism cache key (vs creating a new cache entry on each `readFragment` call)
The solution is not great as it introduces a global variable but don't see how to handle this better with the current setup.
Relates to #113
Note: it is only a partial fix - it leads to 2 vs 4 entries of optimism cache added on click in our example project. But not sure yet where those remaining 2 entries come from. It warrants another round of investigation at some point.

Memoize fragment document for apollo readFragment

---

change/@graphitation-graphql-js-tag-2ba458f3-ff85-44c7-9822-a3825707d79c.json
packages/graphql-js-tag/src/index.ts

This change is required because of Apollo 3.5.x, which isn't able to dedupe queries that contain location data.

Force parser not to generate locations for AST nodes

---

.eslintrc.json

On machines with many cores, `lint` and `test` can run in parralel for `@graphitation/supermassive` project.
This makes sures that __generated__ folders are excluded from lint. As they are part of `.gitignore` already.

Exclude generated files from linting

---

.azure-devops/graphitation-release.yml
change/@graphitation-graphql-eslint-rules-1e6635e6-c781-449f-8f98-a5da413773c7.json
packages/graphql-eslint-rules/package.json

This *should* allow for publishes to go through when pushing changes to git. It also fixes out-of-sync versions.

persist git extra header credentials for publishing purposes

---

.azure-devops/graphitation-release.yml
.azure-devops/steps/pierce-ado-npm-mirror-cache.yml

Still need to add the PAT to the secrets group, looking into ADO CLI now.

[ado] Pierce ADO NPM feed cache for published packages

---

change/@graphitation-supermassive-61be3252-828c-40e6-ab42-e1b52abdc2e8.json
change/@graphitation-ts-transform-graphql-js-tag-6f2150d2-a26a-4f98-be67-070997c04d43.json
examples/supermassive-todomvc/package.json
packages/supermassive/package.json
packages/ts-transform-graphql-js-tag/package.json
yarn.lock

In [current](https://github.com/microsoft/graphitation/blob/dfa894cf781629179c5905adb8fb263035a07e3f/packages/supermassive/package.json#L53) `main` the TS dep is listed as ^4.4.3 , but then it uses a compiler API, which was changed in a breaking manner in [TS 4.5](https://github.com/microsoft/TypeScript/pull/45998), but it uses it in the old manner—i.e. [it passes 2 arguments](https://github.com/microsoft/graphitation/blob/dfa894cf781629179c5905adb8fb263035a07e3f/packages/supermassive/src/extractImplicitTypesToTypescript.ts#L132-L135) instead of 3. For now pinning supermassive to < 4.5, but we should probably be consistent and on latest.

supermassive packages fixes

---

change/@graphitation-apollo-react-relay-duct-tape-07e031f6-0a02-4bf5-bcf9-612af3b991a3.json
packages/apollo-react-relay-duct-tape/src/__tests__/useOverridenOrDefaultApolloClient.test.tsx
packages/apollo-react-relay-duct-tape/src/hooks.ts
packages/apollo-react-relay-duct-tape/src/index.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/compiledHooks/useCompiledFragment.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/compiledHooks/useCompiledLazyLoadQuery.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/compiledHooks/useCompiledPaginationFragment.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/compiledHooks/useCompiledRefetchableFragment.ts
packages/apollo-react-relay-duct-tape/src/useOverridenOrDefaultApolloClient.ts

This allows a subset of a tree to use apollo-react-relay-duct-tape using a different ApolloClient instance than the rest of the tree above and below it.

[duct-tape] Add ability to provide custom apollo client

---

change/@graphitation-graphql-codegen-typescript-typemap-plugin-480de686-21b9-4071-a136-b241ec22edc2.json
change/@graphitation-graphql-js-operation-payload-generator-133357d6-8c45-4d38-a5cd-bf336dabbd96.json
packages/graphql-codegen-typescript-typemap-plugin/.eslintrc.json
packages/graphql-codegen-typescript-typemap-plugin/.npmignore
packages/graphql-codegen-typescript-typemap-plugin/README.md
packages/graphql-codegen-typescript-typemap-plugin/package.json
packages/graphql-codegen-typescript-typemap-plugin/src/index.test.ts
packages/graphql-codegen-typescript-typemap-plugin/src/index.ts
packages/graphql-codegen-typescript-typemap-plugin/tsconfig.json
packages/graphql-js-operation-payload-generator/README.md
packages/graphql-js-operation-payload-generator/package.json
packages/graphql-js-operation-payload-generator/scripts/graphql-codegen.ts
packages/graphql-js-operation-payload-generator/src/__tests__/RelayMockPayloadGenerator.test.ts
packages/graphql-js-operation-payload-generator/src/__tests__/__generated__/schema-types.ts
packages/graphql-js-operation-payload-generator/src/index.ts
packages/graphql-js-operation-payload-generator/src/vendor/RelayMockPayloadGenerator.ts
packages/graphql-js-operation-payload-generator/tsconfig.json
yarn.lock

* Includes a new package that holds a `@graphql-code-generator` plugin that is used to generate a type-map along with schema types, so that they can be enumerated.
* Allow the `MockResolvers` type to be generic and take in a type-map typing, such as the one generated by a plugin like the above.
This will allow an IDE to auto-complete/type-check the type-names used in the mock resolvers map and the output value of the resolvers.

Mock payload generator schema typing

---

change/@graphitation-ts-transform-graphql-js-tag-f621899b-7494-4ed4-93aa-fbaa7d4e3bec.json
packages/ts-transform-graphql-js-tag/package.json
yarn.lock

TMP's webpack/ts-loader setup uses TS 4.3.5, which means we need to target that too or the AST and compiler APIs would be incompatible.

[ts-transform-graphql-js-tag] Make TS req compatible with TMP

---

change/@graphitation-ts-transform-graphql-js-tag-f2a39913-1495-4b07-b4ec-956c2cb435e6.json
packages/ts-transform-graphql-js-tag/src/index.test.ts
packages/ts-transform-graphql-js-tag/src/index.ts

Seems webpack in some cases might compare imports by reference, causing weird duplicate imports.

Fix losing identity of import

---

change/@graphitation-supermassive-3ef8cba5-b4e7-44a5-9be9-fcb9b2e39fe0.json
packages/supermassive/src/ast/__tests__/addTypesToRequestDocument.test.ts
packages/supermassive/src/ast/addTypesToRequestDocument.ts

When running against an updated package, the compiler generated a message to indicate a field was queried that was unknown: "Unhandled: undefined".
This message is not useful - updating the message to output the name of the field makes it possible to find the query with the field and correctly update schema for the new fields.
It would be even better if there was some more metadata that could be added here - the parent type for the field, or the file in which the field occurred.

SuperMassive: AST Error Message fix

---

change/@graphitation-rempl-apollo-devtools-9459664f-a3c5-4ee1-bde1-3e871bd5d9c2.json
packages/rempl-apollo-devtools/scripts/build-separated-bundles.js

set subscriber bundle format to iife in build-separated-bundles.js

Apollo devtools script building fix

---

change/@graphitation-rempl-apollo-devtools-db8f1eac-f13f-4bf8-884d-ac884c389a06.json
packages/rempl-apollo-devtools/src/publisher/publishers/apollo-cache-duplicates-publisher.ts
packages/rempl-apollo-devtools/src/publisher/publishers/apollo-cache-publisher.ts
packages/rempl-apollo-devtools/src/publisher/publishers/apollo-global-operations-publisher.ts
packages/rempl-apollo-devtools/src/publisher/rempl-wrapper.ts
packages/rempl-apollo-devtools/src/subscriber/apollo-recent-activity/recent-activity-container.tsx

If apollo-client's cache is empty and you switched from non-empty client. Then the empty client cache in UI is not updated

Devtools HOTFIXES: empty cache, activity monitor recording and window opener support

---

change/@graphitation-graphql-codegen-typescript-typemap-plugin-2a07ab88-494f-4c59-be10-b7d2a05cba77.json
packages/graphql-codegen-typescript-typemap-plugin/src/index.test.ts
packages/graphql-codegen-typescript-typemap-plugin/src/index.ts
yarn.lock

Add a small fix to be able to generate type map for types with prefix ending with underscore like `OneGQL__`

fix(graphql-codegen-typescript-typemap-plugin): correctly handle types with prefix and underscore

---

change/@graphitation-supermassive-502bf69b-8df9-4b68-82a3-c86b0a4d6081.json
packages/supermassive/src/__tests__/hooks.test.ts
packages/supermassive/src/executeWithSchema.ts
packages/supermassive/src/executeWithoutSchema.ts
packages/supermassive/src/hooks/types.ts
packages/supermassive/src/index.ts
packages/supermassive/src/types.ts
packages/supermassive/src/utilities/array.ts

Initial implementation of the execution hooks:
- beforeFieldResolve
- afterFieldResolve
- afterFieldComplete
Details:
- Each hook accepts in arguments:
- `ResolveInfo` of the field
- Custom context passed into execution (same as passed into resolvers)
- afterResolve/afterComplete also accept resolved value or error
- Hooks aren't invoked for the default field resolvers
- When error is thrown in the hook, it's returned in the response `errors` array

[SUPERMASSIVE] Initial execution hooks implementation

---

change/@graphitation-supermassive-54517af7-4703-4b73-bac9-a77243ba55d9.json
packages/supermassive/src/__tests__/hooks.test.ts
packages/supermassive/src/executeWithoutSchema.ts

Fixes an issue when error is created and added into execution result regardless of the fact that it's happened actually.

[SUPERMASSIVE] fix invalid behavior in execution hooks error handling

---

change/@graphitation-ts-codegen-8abec8ca-8d88-4f4c-b90a-ae78987dd2ec.json
packages/ts-codegen/src/__tests__/index.test.ts
packages/ts-codegen/src/codegen.ts
packages/ts-codegen/src/context/index.ts
packages/ts-codegen/src/inputs.ts
packages/ts-codegen/src/legacyTypes.ts
packages/ts-codegen/src/models.ts
packages/ts-codegen/src/resolvers.ts

Fixing the following stuff found in ts-codegen:
1. Doesn't create enum or input files when there are not inputs or enums defined in the schema
2. Doesn't define unused import statement
3. Fixing the @import directive (imports were missing in ts files)

[TS-CODEGEN] Hotfixes: empty files + unsused imports + @import directive fixed

---

change/@graphitation-supermassive-db783379-b33a-4525-99e2-d733bb7d531c.json
packages/supermassive/src/__tests__/execute.test.ts
packages/supermassive/src/ast/TypedAST.ts
packages/supermassive/src/ast/__tests__/addTypesToRequestDocument.test.ts
packages/supermassive/src/ast/addTypesToRequestDocument.ts
packages/supermassive/src/benchmarks/swapi-schema/resolvers.ts
packages/supermassive/src/benchmarks/swapi-schema/schema.graphql
packages/supermassive/src/values.ts

Missing arguments without defaults were being ignored, now it's not the case.

Fix lack of support for default variables and values in supermassive

---

change/@graphitation-supermassive-2a63c997-1d3f-48b3-97a6-19ebaadb6692.json
packages/supermassive/src/utilities/mergeResolvers.ts

**Bug**:
Currently implemented check for resolvers entry to be plain object fails when resolvers are exported as `export * as Foo from './foo'`
**Fix**:
Use existing `isObjectLike` function from `./jsutils` instead

Use 'isObjectLike' in mergeResolvers

---

change/@graphitation-embedded-document-artefact-loader-b34b447f-c0ae-4ad7-840c-4213efd94c2c.json
packages/embedded-document-artefact-loader/src/__tests__/transform.test.ts
packages/embedded-document-artefact-loader/src/transform.ts

We bail a little early when "anyChanges" is not set as true. This means we skip the offset scanning work done - this speeds up the loader significantly (1 minute vs <1s over 20k files, for example, inside a sizeable repo).

Embedded doc loader: speed this up to only apply work on relevant files

---

change/@graphitation-supermassive-ec5b2b2f-1d23-403c-ada1-291a096723ce.json
packages/supermassive/src/__tests__/execute.test.ts
packages/supermassive/src/executeWithoutSchema.ts
packages/supermassive/src/types.ts

Supermassive V3 has introduced an unintentional breaking change by renaming `fieldNodes` property of `ResolveInfo` type to `fieldGroup`. 
This PR restores backwards compatibility with Supermassive V2 and graphql 16+

Fix unintentional breaking change in supermassive v3

---

change/@graphitation-rempl-apollo-devtools-a88bc040-37bc-4b0a-8e0f-89d3597b0de3.json
packages/rempl-apollo-devtools/package.json
yarn.lock

Add a scroller to Apollo clients window selection.
Issue: When there are lot of apollo clients available, then in a smaller window, some of the apollo clients move out of the view.
In this fix, added a scroller to view all the apollo Clients.

Add a scroller to Apollo clients window selection

---

change/@graphitation-supermassive-9c63a234-a911-4e96-b195-e164bee73a94.json
packages/supermassive/package.json

Invariant is used in a lot of files but isn't declared as a dependency, this causes issues in stricter package managers.

Add invariant as a dependency

---

change/@graphitation-graphql-codegen-supermassive-schema-extraction-plugin-fd47181f-d477-41ec-a1b7-1ef472945482.json
packages/graphql-codegen-supermassive-schema-extraction-plugin/README.md
packages/graphql-codegen-supermassive-schema-extraction-plugin/package.json
packages/graphql-codegen-supermassive-schema-extraction-plugin/src/index.ts

Update our graphql codegen plugin, and make it encode type definitions into compact schema format of Supermassive V3.

Update graphql-codegen-supermassive-schema-extraction-plugin for usage with supermassive v3

---

change/@graphitation-supermassive-8c7afc91-6856-41c9-9dcc-b081f4def405.json
packages/supermassive/src/IncrementalPublisher.ts
packages/supermassive/src/__tests__/__snapshots__/execute.test.ts.snap
packages/supermassive/src/__tests__/execute.test.ts
packages/supermassive/src/benchmarks/swapi-schema/resolvers.ts
packages/supermassive/src/benchmarks/swapi-schema/schema.graphql
packages/supermassive/src/buildFieldPlan.ts
packages/supermassive/src/collectFields.ts
packages/supermassive/src/executeWithoutSchema.ts
packages/supermassive/src/index.ts
packages/supermassive/src/jsutils/getBySet.ts
packages/supermassive/src/jsutils/isSameSet.ts
packages/supermassive/src/jsutils/promiseWithResolvers.ts
packages/supermassive/src/types.ts
packages/supermassive/src/values.ts

Tests in this PR demonstrate a problem found in supermassive v3 with error handling in the root fields. The fix required porting the latest implementation of the defer/stream from upstream graphql-js repo (the old implementation was originally the culprit for this issue).

Fix inconsistency with graphql-js on errors in root-level resolvers

---

change/@graphitation-supermassive-93463287-b917-4722-b3f2-2472eb0c78a2.json
packages/supermassive/src/utilities/__tests__/__snapshots__/decodeASTSchema.test.ts.snap
packages/supermassive/src/utilities/__tests__/decodeASTSchema.test.ts
packages/supermassive/src/utilities/__tests__/fixtures/schemaWithBooleanParameter.ts
packages/supermassive/src/utilities/decodeASTSchema.ts

The following schema encodes correctly.
```graphql
type Query {
person(id: Int!): Person
}
type Person {
name: String!
phones(includeDefault: Boolean = true): [String!]!
}
```
However when trying to decode it it will throw reach the invariant and throw an error.
`Unexpected value for type Boolean: true`
This PR adds a test case for this case and fixes the decoding.
In addition I changed the test case name to be the correct name.

Make decodeASTSchema correctly decode encoded Booleans

---

change/@graphitation-graphql-codegen-typescript-operations-ee1f4833-5e44-41cc-a3dc-68b5c40ce78a.json
change/@graphitation-ts-codegen-028349d3-a154-4728-acff-92da6d2835f1.json
packages/graphql-codegen-typescript-operations/src/config.ts
packages/graphql-codegen-typescript-operations/src/visitor.ts
packages/ts-codegen/src/__tests__/index.test.ts
packages/ts-codegen/src/context/index.ts
packages/ts-codegen/src/enums.ts

Export string unions as types (added `isTypeOnly` config parameter)

Export string unions as types

---

change/@graphitation-embedded-document-artefact-loader-26192454-96cc-4c82-89dd-3af55914610a.json
packages/embedded-document-artefact-loader/src/__tests__/__snapshots__/webpack.test.ts.snap
packages/embedded-document-artefact-loader/src/__tests__/webpack.test.ts
packages/embedded-document-artefact-loader/src/transform.ts

We can't use this loader with Nova components right now as a parser doesn't understand trailing interpolations in GQL queries and mutation. In this PR I remove these interpolations to pass a parsing logic

Remove trailing interpolations from Nova queries and mutations

---

change/@graphitation-apollo-react-relay-duct-tape-e1ec4234-3d44-4be3-9a6c-4e1bf7a52336.json
packages/apollo-react-relay-duct-tape/README.md
packages/apollo-react-relay-duct-tape/src/__tests__/schema.graphql
packages/apollo-react-relay-duct-tape/src/storeObservation/__tests__/__generated__/compiledHooks_Root_executionQuery.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/__tests__/__snapshots__/compiledHooks.test.tsx.snap
packages/apollo-react-relay-duct-tape/src/storeObservation/__tests__/compiledHooks.test.tsx
packages/apollo-react-relay-duct-tape/src/storeObservation/compiledHooks/useCompiledFragment.ts

The aim of this PR is to fix an issue discovered while integrating refetchable fragments for Jana in TMP. In scope of this PR we:
* make sure that if there is an id variable on the query, it doesn't override the `id` used on the compiled fragment (reordering of spread and id in `useCompiledFragment`)
* add one more invariant, checking if `observableQuery` returned partial result (and failing in such case)
* add another invariant in case of data returned being null
* update readme about cache configuration

fix(apollo-react-relay-duct-tape): use correct id for compiler fragment, add check for partial result

---

change/@graphitation-supermassive-3b9224f6-63b1-455e-9a0f-6a0767000e7b.json
packages/supermassive/src/__tests__/hooks.test.ts
packages/supermassive/src/executeWithoutSchema.ts
packages/supermassive/src/hooks/types.ts
packages/supermassive/src/index.ts

* Introduce custom execution hooks context.
* `afterFieldResolve` hook is now called right after resolver function returns; its `result` argument could now be a promise (for async resolvers).
* Export some `jsutils` functions, like `pathToArray`, `printPathArray` and `isPromise`.

[SUPERMASSIVE] Execution hooks context

---

change/@graphitation-webpack-loader-5a513307-cab6-4b02-8810-88af0fd47328.json
packages/webpack-loader/src/__tests__/loader.test.ts
packages/webpack-loader/src/index.ts

JSON.parse was a minor perf optimization, but it is not compatible with some combinations of options.

remove JSON.parse from webpack-loader

---

change/@graphitation-apollo-react-relay-duct-tape-9dea7f0e-c9d4-4e73-9327-8ef4ebb425b7.json
change/@graphitation-apollo-react-relay-duct-tape-compiler-e4f8cfe1-d73c-45b6-8e06-3ac5db6c1920.json
examples/apollo-watch-fragments/src/__generated__/AppQuery.graphql.ts
examples/apollo-watch-fragments/src/__generated__/TodoListFooter_todosFragment.graphql.ts
examples/apollo-watch-fragments/src/__generated__/TodoListPaginationQuery.graphql.ts
examples/apollo-watch-fragments/src/__generated__/TodoList_nodeFragment.graphql.ts
examples/apollo-watch-fragments/src/__generated__/TodoRefetchQuery.graphql.ts
examples/apollo-watch-fragments/src/__generated__/Todo_todoFragment.graphql.ts
examples/supermassive-todomvc/src/components/__generated__/TodoFragment.graphql.ts
examples/supermassive-todomvc/src/components/__generated__/TodoListQuery.graphql.ts
examples/supermassive-todomvc/src/components/__generated__/TodoUpdatesSubscription.graphql.ts
packages/apollo-react-relay-duct-tape-compiler/src/typeGenerator.ts
packages/apollo-react-relay-duct-tape/src/__tests__/__generated__/hooksTestFragment.graphql.ts
packages/apollo-react-relay-duct-tape/src/__tests__/__generated__/hooksTestMutation.graphql.ts
packages/apollo-react-relay-duct-tape/src/__tests__/__generated__/hooksTestQuery.graphql.ts
packages/apollo-react-relay-duct-tape/src/__tests__/__generated__/hooksTestSubscription.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/__tests__/__generated__/compiledHooks_BackwardPaginationFragment.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/__tests__/__generated__/compiledHooks_BackwardPaginationFragment_PaginationQuery.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/__tests__/__generated__/compiledHooks_ChildFragment.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/__tests__/__generated__/compiledHooks_ForwardPaginationFragment.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/__tests__/__generated__/compiledHooks_ForwardPaginationFragment_PaginationQuery.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/__tests__/__generated__/compiledHooks_QueryTypeFragment.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/__tests__/__generated__/compiledHooks_RefetchableFragment.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/__tests__/__generated__/compiledHooks_RefetchableFragment_RefetchQuery.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/__tests__/__generated__/compiledHooks_Root_executionQuery.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/shallowCompareFragmentReferences.ts
packages/apollo-react-relay-duct-tape/src/types.ts

In Relay Compiler >=15.0.0, the generated types have two differences:
- `$fragmentSpreads` instead of `$fragmentRefs` 
- `$fragmentType` instead of `$refType`
Here you can see an example, of the same file, once generated with duct-tape-compiler and once with relay-compiler (>=15.0.0)
| duct-tape-compiler  |  relay-compiler  |
|---|---|
| ![image](https://github.com/microsoft/graphitation/assets/43915731/7e0f47e1-34df-40e2-87dc-9d90216f5317) | ![image](https://github.com/microsoft/graphitation/assets/43915731/8d409391-d62d-42d8-b42c-f17c604071f2)  |
The scope of this PR is to align those types with the latest version, so other apps will avoid having typescript differences between those versions

Align generated types with relay-compiler >=15.0.0

---

change/@graphitation-graphql-eslint-rules-9e96ee74-8abf-4996-b769-fbdabc593ca5.json
packages/graphql-eslint-rules/src/missing-apollo-key-fields.ts

Removes unused check in the lint rule that breaks in newer version of the plugin.

Fix rule compatibility with newer version of graphql-eslint plugin

---

change/@graphitation-embedded-document-artefact-loader-12b10da8-592d-4657-b0b2-50a40585c63d.json
packages/embedded-document-artefact-loader/README.md
packages/embedded-document-artefact-loader/src/__tests__/ts-jest.test.ts
packages/embedded-document-artefact-loader/src/ts-jest.ts

Adds support for explicitly passing `artifactDirectory` option in jest-config when using artifactDirectory in relay config.

Add artifactDirectory option support to embedded-document-artefact-loader/ts-jest

---

change/@graphitation-supermassive-9ce86754-6e03-40f7-b3aa-aff8ceddef1f.json
packages/supermassive/src/__tests__/hooks.test.ts
packages/supermassive/src/executeWithoutSchema.ts
packages/supermassive/src/hooks/types.ts
packages/supermassive/src/jsutils/printPathArray.ts

- Revert back afterFieldResolve hook invocation way: it is called now when the field is actually resolved.
- Do not call execution hooks for `__typename`.
- Minor improvements in `printPathArray`: remove beginning `.` and use `+=` instead of map/join to speed up strings merging.

Revert afterFieldResolve hook invocation

---

change/@graphitation-graphql-eslint-rules-ef083cdd-ec57-4bfc-a21c-9f93a7724b0e.json
packages/graphql-eslint-rules/src/__tests__/__snapshots__/non-nullable-fields.test.ts.snap
packages/graphql-eslint-rules/src/__tests__/__snapshots__/non-nullable-list-items.test.ts.snap
packages/graphql-eslint-rules/src/__tests__/non-nullable-fields.test.ts
packages/graphql-eslint-rules/src/__tests__/non-nullable-list-items.test.ts
packages/graphql-eslint-rules/src/index.ts
packages/graphql-eslint-rules/src/non-nullable-fields.ts
packages/graphql-eslint-rules/src/non-nullable-list-items.ts

Adds new lint rules:
- `non-nullable-fields` - intended to prohibit nullable `id` fields. Since it was too narrow of a use case I made the rule configurable, so it can take a list of fields that for one reason or another shouldn't be nullable.
- `non-nullable-list-items` - does pretty much what the name suggests

Add new rules

---

change/@graphitation-graphql-eslint-rules-a4ed667c-b920-4ee2-b354-0934fed94850.json
packages/graphql-eslint-rules/package.json
packages/graphql-eslint-rules/src/__tests__/__snapshots__/naming-convention.test.ts.snap
packages/graphql-eslint-rules/src/__tests__/naming-convention.test.ts
packages/graphql-eslint-rules/src/index.ts
packages/graphql-eslint-rules/src/naming-convention.ts
yarn.lock

Adds a modified version of [graphql-eslint/naming-convention](https://github.com/dimaMachina/graphql-eslint/blob/master/packages/plugin/src/rules/naming-convention.ts) rule that:
- allows to introduce exception to enum values based on enum name
- adds new `Namespaced_PascalCase` case style

Naming convention rule

---

change/@graphitation-apollo-react-relay-duct-tape-e4565c32-fa04-4278-9f94-be05c63d8325.json
examples/apollo-watch-fragments/src/useChangeTodoStatusMutation.ts
packages/apollo-react-relay-duct-tape/src/__tests__/hooks.test.tsx
packages/apollo-react-relay-duct-tape/src/hooks.ts
yarn.lock

In microsoft/nova-facade#102 we added `onCompleted` callback on mutation committer function. In relay it is available by default but to make duct-tape consistent and to be able to use the callback in Apollo based Nova components, we need to have in duct tape as well.
Verified using a unit tests and locally in `apollo-watch-fragments` example

feat(apollo-react-relay-duct-tape): add onCompleted callback to mutation

---

change/@graphitation-apollo-react-relay-duct-tape-dec4e85d-2d4f-451d-abee-b802e11ab911.json
packages/apollo-react-relay-duct-tape/src/storeObservation/__tests__/__generated__/compiledHooks_ForwardPaginationFragment_PaginationQuery.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/__tests__/__generated__/compiledHooks_Root_executionQuery.graphql.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/__tests__/__snapshots__/compiledHooks.test.tsx.snap
packages/apollo-react-relay-duct-tape/src/storeObservation/__tests__/compiledHooks.test.tsx
packages/apollo-react-relay-duct-tape/src/storeObservation/compiledHooks/useCompiledPaginationFragment.ts
packages/apollo-react-relay-duct-tape/src/storeObservation/compiledHooks/useCompiledRefetchableFragment.ts
yarn.lock

When query variables change for the scenario where the variables are not set as defaults, the refetch function uses old variables instead of new variables and data is not fetched again. This is caused by the `fragmentReferenceWithOwnVariables` and `refetch` function missing as part of the useCallback dependencies. This PR adds those dependencies to fix it

Fix refetch function to use new variables instead of old ones 

---

examples/supermassive-todomvc/package.json
yarn.lock

We have a High Vulnerability highlighted by our Component Governance check on the `webpack-dev-server` dependency. I'm upgrading the version of it to `^4.13.3` which is already used in the `graphitation` project.

Upgrade web-dev-server on supermassive-todomvc

---

change/@graphitation-apollo-forest-run-20b75c12-cc0e-4285-90e6-ea25ea00f528.json
packages/apollo-forest-run/src/diff/diffErrorKind.ts
packages/apollo-forest-run/src/diff/differenceKind.ts
packages/apollo-forest-run/src/diff/types.ts
packages/apollo-forest-run/src/values/types.ts
packages/apollo-forest-run/src/values/valueKind.ts

Our monorepo builds sources using ESBuild, which doesn't support const enum inlining for typescript: https://github.com/evanw/esbuild/issues/128#issuecomment-1002341244
A quote from there:
> 4. Cross-module inlining only works when bundling
We don't bundle the code with ESBuild, just building ESM from TS, so const enums are not inlined in practice.
This PR implements an alternative approach by replacing const enums with wildcard ES module imports (with re-exports). By itself it doesn't change much, but when combined with minifers like Terser (in the actual bundler), inlining does occur.

refactor(apollo-forest-run): replace const enums with ES modules

---

change/@graphitation-apollo-forest-run-2d5f966b-964e-4a9f-b6dd-0c63051a3137.json
packages/apollo-forest-run/src/ForestRun.ts

Align ForestRun behavior of `read` method with that of the InMemoryCache: InMemoryCache doesn't call `diff` under the hood of the `read` method. 
This difference may cause subtle effects when extending cache classes and wrapping/overriding methods, e.g. for telemetry.

fix(apollo-forest-run): improve compatibility with apollo

---

change/@graphitation-cli-66b66740-d897-4e21-9dce-9f452b45a900.json
change/@graphitation-ts-codegen-c09b79fd-44a4-492e-8b1d-f18202a82cd3.json
packages/cli/src/supermassive.ts
packages/ts-codegen/src/__tests__/context.test.ts
packages/ts-codegen/src/__tests__/index.test.ts
packages/ts-codegen/src/codegen.ts
packages/ts-codegen/src/context/index.ts
packages/ts-codegen/src/context/utilities.ts
packages/ts-codegen/src/resolvers.ts
packages/ts-codegen/src/utilities.ts

New parameters which are used to build imports of the context types are introduced
By default all context types are `unknown by default`. This is an option to apply a different type
```
--context-type-path [contextTypePath]
--context-type-name [contextTypeName]
```
used as -> `import { ${contextTypeName} from "${contextTypePath}"`
Newly there is an option to attach resources to fields using @context directive.
```
directive @context(
uses: [String!]!
) on FIELD_DEFINITION | OBJECT | UNION | INTERFACE
```
A type used for extending every resource type.
```
--default-context-sub-type-path [defaultContextSubTypePath]
--default-context-sub-type-name [defaultContextSubTypeName]
```
used as -> `import { ${defaultContextSubTypeName} from "${defaultContextSubTypePath}"`
Template for resource …

[TS-CODEGEN] context types generation re-work

---

change/@graphitation-apollo-forest-run-f9506eab-d2d4-4832-a8e0-2d9b33f81a18.json
packages/apollo-forest-run/src/ForestRun.ts
packages/apollo-forest-run/src/cache/env.ts
packages/apollo-forest-run/src/cache/read.ts
packages/apollo-forest-run/src/cache/store.ts
packages/apollo-forest-run/src/cache/types.ts
packages/apollo-forest-run/src/cache/write.ts
packages/apollo-forest-run/src/forest/types.ts

ForestRun evicts older trees automatically using LRU strategy. But the strategy before this PR was somewhat magical, using LRUMap for "trees" data. Basically any access to the via map `.get()` method caused the tree to be touched. This doesn't work well in certain cases. Plus, eviction happens in random moments and it is hard to control.
This PR exposes eviction as an explicit step in transaction as soon as forest size reaches a threshold for eviction. This way we have better control over it, and can adjust additional scenarios where we want to keep data in cache longer (e.g. with duct-tape integration)

ForestRun: Explicit LRU eviction as a part of write transaction

---

change/@graphitation-apollo-forest-run-07cc18c7-3acd-465a-bb5f-c0c1131a7052.json
packages/apollo-forest-run/src/ForestRun.ts
packages/apollo-forest-run/src/cache/store.ts

ForestRun cleans up old unused trees automatically as soon as cache size reaches a certain threshold. But sometimes it makes sense to not wait and call cleanup explicitly. Apollo already has `gc()` method in its abstract ApolloCache class. In this PR we expose `ForestRun` cleanup via this method.

ForestRun: Expose data cleanup through Apollo gc() method

---

.azure-devops/graphitation-release.yml

Do not use PAT token for our service account and use persistCredentials instead.

feat(pipelines): set persistCredentials for beachball

---

change/@graphitation-cli-04e7c1c5-55ca-43a0-9831-99c6ce2c08a6.json
change/@graphitation-ts-codegen-f56151b9-3e03-44fa-a6df-2a49bf549a15.json
packages/cli/.gitignore
packages/cli/src/__tests__/__snapshots__/typeDefsToImplicitResolvers.test.ts.snap
packages/cli/src/__tests__/typeDefsToImplicitResolvers.test.ts
packages/cli/src/supermassive.ts
packages/ts-codegen/README.md
packages/ts-codegen/package.json
packages/ts-codegen/src/__tests__/context.test.ts
packages/ts-codegen/src/__tests__/index.test.ts
packages/ts-codegen/src/codegen.ts
packages/ts-codegen/src/context/index.ts
packages/ts-codegen/src/resolvers.ts

1. new `--generate-resolver-map` flag
2. Extracted options types for ts-codegen and remove duplications
3. CLI test for ts-codegen
When the flag is enabled we are generating default export for resolvers
```ts
export default interface ResolversMap {
readonly User?: User.Resolvers;
readonly Query?: Query.Resolvers;
}
```
note for `legacyEnumsCompatibility` the key was renamed https://github.com/microsoft/graphitation/pull/345 and therefore the test are not testing anything so it was removed in this PR.

feat(ts-codegen): option for default export

---

change/@graphitation-apollo-forest-run-b3e52c0c-9b15-451a-bf65-ecb0ce45aa97.json
packages/apollo-forest-run/src/ForestRun.ts

In some cases results after a transaction end up being equal to the last notified diff.
In this case we shouldn't notify watchers, but we do. This PR is just a quick-fix. My initial assumption was that the scenario where data is equal, but not strictly equal is not possible with FR, but so far it seems to be possible.
The proper fix requires further investigation and reproduction of the scenario where this is possible.

fix: prevent excessive re-renders in ForestRun

---

change/@graphitation-apollo-forest-run-e9ffb57c-ed0c-4c9f-8ea6-e14822696d37.json
packages/apollo-forest-run/src/__tests__/eviction.test.ts
packages/apollo-forest-run/src/cache/env.ts
packages/apollo-forest-run/src/cache/store.ts
packages/apollo-forest-run/src/cache/types.ts

Today ForestRun does automatic data eviction when the number of operation exceeds `maxOperationResult` option. This PR introduces an `autoEvict` option which allows disabling automated eviction and instead control when data eviction kicks in with `gc` method from Apollo cache interface.
Related options:
- `autoEvict`: default `true`
- `maxOperationCount`: default `1000`

feat: configurable auto-eviction

---

change/@graphitation-embedded-document-artefact-loader-0a728686-32d8-44df-9101-e88cfeffd469.json
packages/embedded-document-artefact-loader/src/ts-jest.ts

Currently, placing a line debugger in a file transformed by ts-jest causes issues with positioning, resulting in the debugger opening the transformed file instead of the original one. A similar behavior occurs with the debugger keyword, which also opens the transformed file.
To address this, we need to place inline source maps for code editors. While ts-jest generates these inline source maps, we have been extracting them and merging them with our source maps from the transformed files, but we have never applied them as inline source maps.

fix(ts-jest): source maps for debug

---

change/@graphitation-apollo-forest-run-236a4676-ef3a-46e7-8d83-e276c80d94de.json
packages/apollo-forest-run/src/__tests__/helpers/mock.ts
packages/apollo-forest-run/src/values/__tests__/draft.test.ts
packages/apollo-forest-run/src/values/execute.ts

This PR fixes a quirk of ForestRun that was known before, but proved to be really detrimental for perf in some edge cases in the real world app.
In short, embedded objects (i.e. objects without ids) could be wastefully re-visited many times while reading object value in presence of missing fields (which is common with duct-tape and some other scenarios).
Here we simply track which objects were visited during read and don't re-visit them again.

fix(apollo-forest-run): do not visit the same chunk twice when reading

---

change/@graphitation-apollo-forest-run-7cc0912b-29df-4ac9-b632-88364bf55c93.json
packages/apollo-forest-run/src/cache/write.ts

Fixes an incorrect assumption causing `Invariant violation` error in some niche "write" scenarios with ForestRun (when operation has keyVariables and key descriptor is removed after eviction, but non-key one remains in the cache).

fix(apollo-forest-run): use replaceTree vs addTree on write

---

change/@graphitation-apollo-react-relay-duct-tape-9a499138-bae3-4fd0-a527-d52c6abfd72f.json
packages/apollo-react-relay-duct-tape/src/storeObservation/__tests__/compiledHooks.test.tsx
packages/apollo-react-relay-duct-tape/src/storeObservation/compiledHooks/useCompiledLazyLoadQuery.ts

We are unsubscribing only if the state is not loading. In case of store-and-network we get the data immediately and then unsubscribe. With this change we returns the data and waits until the request finish.

fix(duct-tape): do not unsubscribe in loading state

---

change/@graphitation-ts-codegen-e8bb23c6-ffa0-420e-ab9d-2c2e593ca434.json
packages/ts-codegen/src/__tests__/index.test.ts
packages/ts-codegen/src/codegen.ts
packages/ts-codegen/src/context/index.ts
packages/ts-codegen/src/context/utilities.ts
packages/ts-codegen/src/models.ts
packages/ts-codegen/src/resolvers.ts

Prevents `ts-codegen` from emitting empty `model.interface.ts` files and adding unused imports to `resolvers.interface.ts` which could cause ts errors

(feat): do not emit empty models

---

change/@graphitation-graphql-codegen-typescript-typemap-plugin-4db16247-8e9c-48df-aa31-cd602e20f366.json
packages/graphql-codegen-typescript-typemap-plugin/src/__tests__/index.test.ts
packages/graphql-codegen-typescript-typemap-plugin/src/index.ts

`@graphql-codegen/typescript@4.0.0` plugin has introduced a breaking change in how `Scalars` type is generated - instead of a plain name-type map it now includes separate `input` and `output` types (more info is in changelog: <https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/typescript/typescript/CHANGELOG.md#400>).
The TypeMap plugin expects old format and generates `TypeMap` with same `input` and `output` field, which breaks consumers of the plugin.
To recreate old behavior of the plugin, it is updated to generate `Scalars[<name>]["output"]` instead of `Scalars[<name>]`. This is a breaking change for this plugin since it will stop generating valid typescript when used with `@graphql-codegen/typescript` versions prior to 4.0.0.
This will still break for …

fix(graphql-codegen-typescript-typemap-plugin): use output Scalars in TypeMap

---

change/@graphitation-apollo-forest-run-cbad31f8-57fc-45bd-aa03-aa62e543d560.json
package.json
packages/apollo-forest-run/src/jsutils/assert.ts
scripts/inline-assert.ts
scripts/just.config.ts
yarn.lock

`ES2018` is the earliest version which supports object spread syntax, i.e. `{ ...cloned }`. With our current build target (`es6`) we rely on TS polyfill for it which is significantly slower. For perf-sensitive packages like apollo-forest-run it is important.
This takes inspiration from a [similar approach](https://github.com/graphql/graphql-js/blob/0a848cc4c781fb79b2e55eb8d011675dd612524f/resources/inline-invariant.js#L4) taken in graphql-js. In our case it gives us two things:
1. Perf savings due to inlining (`assert` function is not called)
2. Additional debugging info for minified version, or version without access to to stack trace

Change build target to ES2018; inline asserts

---

change/@graphitation-apollo-forest-run-8f579db3-9708-47e4-bcb1-918e7879330d.json
packages/apollo-forest-run/src/__tests__/regression.test.ts
packages/apollo-forest-run/src/cache/write.ts
packages/apollo-forest-run/src/descriptor/operation.ts

Mirror Apollo behavior on incorrect incoming data. For backwards compatiblity

fix(apollo-forest-run): don't throw on incorrect incoming data

---

change/@graphitation-apollo-forest-run-7575015d-b204-4199-bd95-dd0b8d432556.json
packages/apollo-forest-run/src/__tests__/regression.test.ts
packages/apollo-forest-run/src/forest/indexTree.ts

Minor fix for ForestRun to ensure backwards-compatibility with Apollo InMemoryCache when manual write contains incorrect list item.

fix(apollo-forest-run): treat incorrect list items the same way as InMemoryCache

---

change/@graphitation-apollo-mock-client-5bd98313-0cb0-4d3a-ab1c-f35295707e7f.json
change/@graphitation-apollo-react-relay-duct-tape-8dfbf320-25ee-485c-b207-f0e3c3f1ef04.json
change/@graphitation-apollo-react-relay-duct-tape-compiler-22f1ddbf-d0f8-4038-a404-290c580f4dc0.json
change/@graphitation-cli-69344dde-2cdf-4e48-9f29-961f3a5f609d.json
change/@graphitation-embedded-document-artefact-loader-f1a86fc9-e9d5-499b-bbb5-f69b55a3e748.json
change/@graphitation-graphql-codegen-resolvers-models-530e0dde-e6ec-4220-af68-21870f9f7b0a.json
change/@graphitation-graphql-codegen-supermassive-schema-extraction-plugin-f065b011-f163-4f73-9536-d3c578cfee7f.json
change/@graphitation-graphql-codegen-supermassive-typed-document-node-plugin-c293811d-27d4-4b26-82d4-cd95b0136a01.json
change/@graphitation-graphql-codegen-typescript-operations-bc944249-9395-4136-8c4a-0565f3995811.json
change/@graphitation-graphql-codegen-typescript-typemap-plugin-87a1ca71-9690-4c8b-8423-93496c7fc47d.json
change/@graphitation-graphql-eslint-rules-39aa8004-a754-4588-9e89-ac1b399b1575.json
change/@graphitation-graphql-js-operation-payload-generator-78aef08f-7334-4a62-a952-1a852a9bf8b2.json
change/@graphitation-graphql-js-tag-f21ac1ef-6bad-4776-ac04-43ee223f7e93.json
change/@graphitation-rempl-apollo-devtools-c0b0cb98-6a22-4008-a9c4-d0f9ca6c5956.json
change/@graphitation-supermassive-cf61cd51-ab1a-4154-a1a1-a584b3218fd7.json
change/@graphitation-supermassive-extractors-fb1ee13b-90ff-4ebf-a17c-e61f2f7ca3fc.json
change/@graphitation-ts-codegen-15fc1402-48b8-4620-8b22-0c16fd6aa413.json
change/@graphitation-ts-transform-graphql-js-tag-16c48d9c-9397-4706-a04d-161cf09d9927.json
change/@graphitation-webpack-loader-2e33f3f1-359f-4f6e-96f1-fe7e1edbe9dd.json

This is a follow up for https://github.com/microsoft/graphitation/pull/536
In that PR build target in the repo was changed from `ES6` to `ES2018`. Here we bump all packages and publish new minors with new build target (except for `apollo-forest-run` which is already published with new build target)

Bump all packages with new build target - ES2018

---

change/@graphitation-apollo-react-relay-duct-tape-a82ac372-c1f5-4f2b-bd45-8d443375c2c1.json
packages/apollo-react-relay-duct-tape/src/storeObservation/__tests__/compiledHooks.test.tsx
packages/apollo-react-relay-duct-tape/src/storeObservation/compiledHooks/useCompiledRefetchableFragment.ts

We experience a bug in People app where upon using `store-and-network` policy in `useRefetchable/PaginationFragment`'s refetch function, we sometimes don't get the result returned from resolvers. This is very similar issue to #528 and the fix is similar as well, we make sure to not unsubscribe from watched query until it is out of loading state.
Added unit tests which failed before the fix and now works correctly

fix(apollo-react-relay-duct-tape): fix `store-and-network` policy on refetchable fragments

---

.vscode/settings.json
change/@graphitation-apollo-forest-run-9332d398-83bc-460d-a82e-9cbb1f40378f.json
packages/apollo-forest-run/src/ForestRun.ts
packages/apollo-forest-run/src/cache/env.ts
packages/apollo-forest-run/src/cache/keys.ts
packages/apollo-forest-run/src/cache/policies.ts
packages/apollo-forest-run/src/cache/store.ts
packages/apollo-forest-run/src/cache/types.ts
packages/apollo-forest-run/src/forest/types.ts
packages/apollo-forest-run/src/forest/updateObject.ts
packages/apollo-forest-run/src/forest/updateTree.ts
packages/apollo-forest-run/src/jsutils/logger.ts
packages/apollo-forest-run/src/telemetry/types.ts

Replace all `console.log` statements with custom logger. Logger instance can be injected via cache config. The default is equivalent to:
```ts
const cache = new ForestRun({
logger: console
});
```
Passing `logger: undefined` will disable logging (alternatively custom `log`, `debug`, `error`, `warn` methods could be used for fine-grain control over logging).
Add ability to send structured data to telemetry, when corresponding notification handler is set:
```ts
const cache = new ForestRun({
notify: (event) => {
// event contains structured data to be sent to telemetry
}
});
```
All event types are placed under `telemetry/types.ts`

feat(apollo-forest-run): support custom logger and rudimentary telemetry

---

change/@graphitation-apollo-forest-run-68967b17-737e-4a5d-830f-13897f4542f5.json
change/@graphitation-rempl-apollo-devtools-2b2f1543-4ad4-4625-b1ea-393e8ceb3553.json
packages/apollo-forest-run/src/ForestRun.ts
packages/apollo-forest-run/src/ForestRunCompat.ts
packages/apollo-forest-run/src/__tests__/extract.test.ts
packages/apollo-forest-run/src/cache/types.ts
packages/rempl-apollo-devtools/src/publisher/publishers/apollo-cache-publisher.ts
packages/rempl-apollo-devtools/src/publisher/publishers/apollo-operations-tracker-publisher.ts
packages/rempl-apollo-devtools/src/types.ts

Support `extract()` method from ApolloCache interface in ForestRun. Now custom changes we did for DevTools are not necessary, devtools can rely on common interface.

feat(apollo-forest-run): cache extract

---

change/@graphitation-apollo-forest-run-5995c44c-85cd-4b7a-ae10-9ccb7505b4f9.json
packages/apollo-forest-run/src/__tests__/regression.test.ts
packages/apollo-forest-run/src/cache/read.ts

Fixes a bug in ForestRun where root-level `__typename` field comes out of sync for optimistic and non-optimistic result and accidentally breaks `@nonreactive`/`useFragment` scenario.
Apollo InMemoryCache strips away root-level `__typename` on read. Example:
```ts
cache.write({
query: gql`{ foo }`,
result: { __typename: "Query", foo: "foo" }; // <-- Note the `__typename` field
});
const readResult = cache.read({ query, optimistic: true });
```
`readResult` above is `{ foo: "foo" }` (i.e. without the `__typename` field).
(this logic plays a role later when Apollo compares "before/after" results of the same query for equality)
ForestRun on the other hand always preserves the initial result for a query "as-is" (so in ForestRun `readResult` from the example contains `__typename`). But for …

fix(apollo-forest-run): keep root-level __typename in sync when reading

---

change/@graphitation-apollo-forest-run-89f388a7-a766-4e0d-850b-c6910a95227a.json
packages/apollo-forest-run/compat/src/cache/inmemory/__tests__/cache.ts
packages/apollo-forest-run/compat/src/cache/inmemory/__tests__/readFromStore.ts
packages/apollo-forest-run/src/__tests__/regression.test.ts
packages/apollo-forest-run/src/cache/read.ts

A follow up for https://github.com/microsoft/graphitation/pull/553 with a different approach, as the original one turned out to be incomplete in some edge cases.

fix(apollo-forest-run): other approach for consistent root-level __typename

---

change/@graphitation-apollo-forest-run-0b0b8357-664b-4c02-a8b9-1c3ecd2a2032.json
packages/apollo-forest-run/src/__tests__/regression.test.ts
packages/apollo-forest-run/src/cache/write.ts

Fixes a bug in ForestRun where fragments on abstract types were not being written correctly. That was caused by ForestRun relying on fragment type condition instead of the actual `__typename` from the store for abstract types.

fix(apollo-forest-run): correctly write fragments on abstract types

---

change/@graphitation-cli-9d74464b-d6d4-47f3-af75-eb0380d27a3d.json
change/@graphitation-ts-codegen-35e832ce-c9de-4ac0-9b68-b90e373b4573.json
packages/cli/src/supermassive.ts
packages/ts-codegen/src/__tests__/context.test.ts
packages/ts-codegen/src/codegen.ts
packages/ts-codegen/src/context/index.ts
packages/ts-codegen/src/context/utilities.ts
packages/ts-codegen/src/index.ts
packages/ts-codegen/src/resolvers.ts
packages/ts-codegen/src/utilities.ts

We want to enable people to define the resolver context subtypes  with namespaces.
Expected input: 
--context-sub-type-metadata-file
```
{
baseContextTypePath: "@package/default-context",
baseContextTypeName: "DefaultContextType",
contextTypes: {
managers: {
user: {
importNamespaceName: "UserStateMachineType",
importPath: "@package/user-state-machine",
},
whatever: {
importPath: "@package/whatever-state-machine",
},
}
```

[ts-codegen] Implement context types with namespaces defined in the input file

---

change/@graphitation-cli-eb21eb0e-6d37-4abf-8ea8-d5a247f340c5.json
change/@graphitation-ts-codegen-1fee3f38-7bd0-4a6d-87cc-67d36aa688d6.json
packages/cli/src/supermassive.ts
packages/ts-codegen/src/__tests__/context.test.ts
packages/ts-codegen/src/codegen.ts
packages/ts-codegen/src/context/index.ts

Will newely accept typeName field for more variability.
```   
const contextTypeExtensions = {
baseContextTypePath: "@package/default-context",
baseContextTypeName: "DefaultContextType",
contextTypes: {
managers: {
user: {
importNamespaceName: "UserStateMachineType",
importPath: "@package/user-state-machine",
typeName: 'UserStateMachineType["user"]',
},
whatever: {
importPath: "@package/whatever-state-machine",
typeName: "whatever",
},
"different-whatever": {
importNamespaceName: "DifferentWhateverStateMachineType",
importPath: "@package/different-whatever-state-machine",
typeName:
'DifferentWhateverStateMachineType["managers"]["different-whatever"]',
}
}
}         
```

ts-codegen resolver context types will be defined explicitly in the input file

---

change/@graphitation-apollo-forest-run-a3bbed5c-144a-4ae0-a4a9-dde6c5648e17.json
packages/apollo-forest-run/src/ForestRun.ts
packages/apollo-forest-run/src/__tests__/extract.test.ts

Fixes exception `Invalid value used as weak map key` when optimistic node has no corresponding entry in the actual data forest.

fix(apollo-forest-run): fix bogus optimistic data extract

---

change/@graphitation-apollo-forest-run-d9f1ba9c-10a0-41c3-8f4c-8bb0c623ead5.json
packages/apollo-forest-run/compat/src/cache/inmemory/__tests__/optimistic.ts
packages/apollo-forest-run/src/__tests__/regression.test.ts
packages/apollo-forest-run/src/cache/draftHelpers.ts
packages/apollo-forest-run/src/cache/read.ts
packages/apollo-forest-run/src/cache/types.ts

Before this fix, fragment writes inside optimistic transaction were not handled properly due to incorrect chunk recycling from other layers. 
In many cases optimistic fragment writes are accompanied by query updates (via `update` or `updateQuery` callbacks). Those cases where working as expected.
However an individual optimistic fragment write (without any additional query update) was causing an issue, because optimistic layer ended up only having a fragment without any root-level query, thus making the updated optimistic node unreachable.
I.e. instead of actually applying updated node to affected queries, we were recycling query results from the main layer without changes.
The fix is to take into account both dirty nodes _and_ their parents (including root-level query nodes) when …

fix(apollo-forest-run): apply optimistic fragment writes correctly

---

change/@graphitation-cli-daecf3a3-3287-4687-835d-9c44acbce968.json
change/@graphitation-ts-codegen-6545cc24-06ec-443b-94ca-42f154d74e98.json
packages/cli/src/supermassive.ts
packages/ts-codegen/src/__tests__/context.test.ts
packages/ts-codegen/src/codegen.ts
packages/ts-codegen/src/context/index.ts
packages/ts-codegen/src/context/utilities.ts
packages/ts-codegen/src/resolvers.ts

New way how to define whether ten sub context type is optional or not
```
@context(
required: { managers: [
"managerA"
"managerB"
]
},
optional: {...}
)
```
New way of pre-defining groups which then can be used as custom directive. It will 
```
const contextTypeExtensions = {
baseContextTypePath: "@package/default-context",
baseContextTypeName: "DefaultContextType",
groups: {
UserTestGroup: {
managers: ["user", "whatever"],
},
PostTestGroup: {
managers: ["post", "whatever"],
workflows: ["post-workflow"],
},
},
....
```
Usage of the grouping:
```
extend type Query {
requiredUsers: [User!]! @UserTestGroup
optionalUsers: [User] @UserTestGroup
optionalUser: User
@context(
required: { managers: ["user"] }
optional: { managers: ["node"] }
)
requiredUser: User! @context(optional: { managers: …
```

Codegen supports resolver context conditionality and creating groups in input file

---

.vscode/settings.json
change/@graphitation-apollo-forest-run-b8abfe6c-acee-4443-bd26-fcc6eef53b42.json
packages/apollo-forest-run/src/__tests__/eviction.test.ts
packages/apollo-forest-run/src/cache/env.ts
packages/apollo-forest-run/src/cache/store.ts
packages/apollo-forest-run/src/cache/types.ts
packages/apollo-forest-run/src/jsutils/logger.ts

Allows us to put items in different buckets for purposes of eviction/retention. 
This would retain a max of 500 "default partition" items and an independent 120 "CriticalChatQueries" items.
Example:
```ts
maxOperationCount: 500,
partitionConfig: {
partitionKey: op => {
switch (op.operation.debugName) {
case "query ChatMetadataQuery":
case "query ChatMessageListQuery":
case "query ChatAppsQuery":
return "CriticalChatQueries";
}
return;
},
partitions: {
CriticalChatQueries: {
maxOperationCount: 120,
},
},
},
```
or
```ts
maxOperationCount: 500,
partitionConfig: {
partitionKey: op => {
const rootFields = getRootFields(op);
if (["messages", "chat", "apps"].some(field => rootFields?.has(field))) {
return "CriticalChatQueries";
}
return;
},
partitions: {
CriticalChatQueries: { …
```

feat(apollo-forest-run): introduce partitions for evictions

---

change/@graphitation-cli-861171b5-d2d8-4e42-bc33-a92a43e9c6ae.json
change/@graphitation-ts-codegen-de89350f-123c-4d95-9bd1-9481317433fd.json
packages/cli/src/supermassive.ts
packages/ts-codegen/src/__tests__/context.test.ts
packages/ts-codegen/src/context/index.ts
packages/ts-codegen/src/types.ts

Groups in contextExtensions changed shape to support useLegacy:
```
...
groups: {
baseContextOnly: {},
UserTestGroup: {
required: {
managers: ["user", "whatever"],
},
},
PostTestGroup: {
required: {
managers: ["post", "whatever"],
workflows: ["post-workflow"],
},
},
PostTestGroupWithLegacyContext: {
useLegacy: true,
required: {
managers: ["post", "whatever"],
workflows: ["post-workflow"],
},
},
},
...
```

[HOTFIX] group isLegacy param renamed to useLegacy
